//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PineWealth.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PineWealth.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //@version=4
        ///strategy(&quot;RSI Overbought/Oversold&quot;, overlay=true)
        ///
        ///rsi = ta.rsi(close, 14)
        ///
        ///if (rsi &gt; 70)
        ///    strategy.entry(&quot;Short&quot;, strategy.short)
        ///
        ///if (rsi &lt; 30)
        ///    strategy.entry(&quot;Long&quot;, strategy.long).
        /// </summary>
        internal static string PineScript {
            get {
                return ResourceManager.GetString("PineScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using WealthLab.Backtest;
        ///using System;
        ///using WealthLab.Core;
        ///using WealthLab.Data;
        ///using WealthLab.Indicators;
        ///using System.Collections.Generic;
        ///
        ///namespace WealthScript1 
        ///{
        ///    public class MyStrategy : UserStrategyBase
        ///    {
        ///        //create indicators and other objects here, this is executed prior to the main trading loop
        ///        public override void Initialize(BarHistory bars)
        ///        {
        ///            &lt;#Initialize&gt;
        ///        }
        ///
        ///        //execute the strategy rules here, this is executed once [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PineScriptCSharp {
            get {
                return ResourceManager.GetString("PineScriptCSharp", resourceCulture);
            }
        }
    }
}
